name: Install

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install package on ${{ matrix.python-version }}
      uses: ./.github/actions/install
      with:
        python-version: ${{ matrix.python-version }}
